name: build CI
on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: npm

      - name: Build src
        run: |
          cp server-config/.env.dev .env.production
          npm ci
          npm run build
